services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --noreload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
